{% set name = "mesmer" %}
{% set pypiname = "mesmer-emulator" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 6828a76cb5a8870ca3a005a61a05a5de2befca3616241c2d37d822aed63a5b0d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - dask
    - distributed
    - geopy
    - joblib
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - statsmodels
    - regionmask
    - xarray

test:
  imports:
    - mesmer
  requires:
    - pip
  commands:
    - pip check
    - python -c "import mesmer; assert mesmer.__version__ == '{{ version }}', mesmer.__version__"

about:
  home: https://github.com/MESMER-group/mesmer
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Modular Earth System Model Emulator with spatially Resolved output
  doc_url: https://mesmer-emulator.readthedocs.io/en/stable/
  dev_url: https://github.com/MESMER-group/mesmer

extra:
  recipe-maintainers:
    - znicholls
    - mathause
